export const leftNavData = [{
    id: 'home',
    path: '/storeManage/echarts',
    name: '首页',
    iconType: 'antd',
    icon: 'home',
    query: {},
  },
  {
    id: 'userManage',
    path: '/userManage',
    name: '待办事项',
    iconType: 'antd',
    icon: 'team',
    query: {},
    children: [{
        id: 'userManageList',
        path: '/userManage/list',
        name: '待办任务处理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList1',
        path: '/home',
        name: '待办任务退签',
        iconType: 'antd',
        icon: '',
        query: {},
      },
    ]
  },
  {
    id: 'userManage1',
    path: '/home2',
    name: '样本库管理',
    iconType: 'antd',
    icon: 'user',
    query: {},
    children: [{
        id: 'userManageList2',
        path: '/home',
        name: '样本入库',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList3',
        path: '/home',
        name: '样本出库',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList4',
        path: '/home',
        name: '容器设置',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList5',
        path: '/home',
        name: '样本出库详情',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList6',
        path: '/home',
        name: '样本入库详情',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList7',
        path: '/home',
        name: '样本库列表',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList8',
        path: '/home',
        name: '样本库视图',
        iconType: 'antd',
        icon: '',
        query: {},
      },
    ]
  },
  {
    id: 'userManage2',
    path: '/home3',
    name: '收样管理',
    iconType: 'antd',
    icon: 'form',
    query: {},
    children: [{
        id: 'userManageList9',
        path: '/home',
        name: '样本接收',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList10',
        path: '/home',
        name: '样本拆分',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList11',
        path: '/home',
        name: '异常处理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList12',
        path: '/home',
        name: '样本查询',
        iconType: 'antd',
        icon: '',
        query: {},
      }

    ]
  },
  {
    id: 'userManage3',
    path: '/home4',
    name: '订单列表',
    iconType: 'antd',
    icon: 'copy',
    query: {},
    children: [{
      id: 'userManageList13',
      path: '/home',
      name: '审核，立项，修改，取消',
      iconType: 'antd',
      icon: '',
      query: {},
    }]
  },

  {
    id: 'userManage4',
    path: '/home5',
    name: '变动订单',
    iconType: 'antd',
    icon: 'scissor',
    query: {},
    children: [{
      id: 'userManageList14',
      path: '/home',
      name: '新冠订单管理',
      iconType: 'antd',
      icon: '',
      query: {},
    }]
  },
  {
    id: 'userManage5',
    path: '/home6',
    name: '返样管理',
    iconType: 'antd',
    icon: 'snippets',
    query: {},
    children: [{
      id: 'userManageList15',
      path: '/home',
      name: '返样管理',
      iconType: 'antd',
      icon: '',
      query: {},
    }]
  },
  {
    id: 'userManage6',
    path: '/home7',
    name: '重新送样',
    iconType: 'antd',
    icon: 'highlight',
    query: {},
    children: [{
      id: 'userManageList16',
      path: '/home',
      name: '重新送样',
      iconType: 'antd',
      icon: '',
      query: {},
    }]
  },
  {
    id: 'userManage7',
    path: '/home8',
    name: '打包列表',
    iconType: 'antd',
    icon: 'diff',
    query: {},
    children: [{
      id: 'userManageList17',
      path: '/home',
      name: '打包列表',
      iconType: 'antd',
      icon: '',
      query: {},
    }]
  },
  {
    id: 'userManage8',
    path: '/home9',
    name: '项目异常',
    iconType: 'antd',
    icon: 'fund',
    query: {},
    children: [{
      id: 'userManageList18',
      path: '/home',
      name: '项目异常',
      iconType: 'antd',
      icon: '',
      query: {},
    }]
  },
  {
    id: 'userManage9',
    path: '/home10',
    name: '报告管理系统',
    iconType: 'antd',
    icon: 'alert',
    query: {},
    children: [{
        id: 'userManageList19',
        path: '/home',
        name: '报告生成或上传',
        iconType: 'antd',
        icon: '',
        query: {},
      }, {
        id: 'userManageList20',
        path: '/home',
        name: '报告审核',
        iconType: 'antd',
        icon: '',
        query: {},
      }, {
        id: 'userManageList21',
        path: '/home',
        name: '报告批准',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList22',
        path: '/home',
        name: '报告发送',
        iconType: 'antd',
        icon: '',
        query: {},
      }
    ]
  },
  {
    id: 'userManage10',
    path: '/home11',
    name: '实验进度',
    iconType: 'antd',
    icon: 'apartment',
    query: {},
    children: [{
        id: 'userManageList21',
        path: '/home',
        name: '进行中',
        iconType: 'antd',
        icon: '',
        query: {},
      }, {
        id: 'userManageList22',
        path: '/home',
        name: '已完成',
        iconType: 'antd',
        icon: '',
        query: {},
      }, {
        id: 'userManageList22',
        path: '/home',
        name: '异常实验',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList23',
        path: '/home',
        name: '全部',
        iconType: 'antd',
        icon: '',
        query: {},
      }
    ]
  },
  {
    id: 'userManage11',
    path: '/home12',
    name: '样本处理',
    iconType: 'antd',
    icon: 'bank',
    query: {},
    children: [{
        id: 'userManageList23',
        path: '/home',
        name: '病理质控',
        iconType: 'antd',
        icon: '',
        query: {},
      }, {
        id: 'userManageList24',
        path: '/home',
        name: '核酸提取',
        iconType: 'antd',
        icon: '',
        query: {},
      }

    ]
  },

  {
    id: 'userManage12',
    path: '/home13',
    name: '实验任务',
    iconType: 'antd',
    icon: 'bell',
    query: {},
    children: [{
        id: 'userManageList25',
        path: '/home',
        name: '新冠实验任务管理',
        iconType: 'antd',
        icon: '',
        query: {},
      }, {
        id: 'userManageList26',
        path: '/home',
        name: 'NGS实验任务管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList27',
        path: '/home',
        name: 'QPCR实验管理',
        iconType: 'antd',
        icon: '',
        query: {},
      }, {
        id: 'userManageList28',
        path: '/home',
        name: 'ddPCR实验管理',
        iconType: 'antd',
        icon: '',
        query: {},
      }, {
        id: 'userManageList29',
        path: '/home',
        name: 'MLPA实验管理',
        iconType: 'antd',
        icon: '',
        query: {},
      }, {
        id: 'userManageList30',
        path: '/home',
        name: 'sanger测序实验管理',
        iconType: 'antd',
        icon: '',
        query: {},
      }, {
        id: 'userManageList31',
        path: '/home',
        name: '实验外包管理',
        iconType: 'antd',
        icon: '',
        query: {},
      }, {
        id: 'userManageList32',
        path: '/home',
        name: '各平台报告生成或上传',
        iconType: 'antd',
        icon: '',
        query: {},
      },
    ]
  },
  {
    id: 'userManage13',
    path: '/home14',
    name: '实验统计',
    iconType: 'antd',
    icon: 'block',
    query: {},
    children: [{
        id: 'userManageList33',
        path: '/home',
        name: '实验完成情况统计',
        iconType: 'antd',
        icon: '',
        query: {},
      }, {
        id: 'userManageList34',
        path: '/home',
        name: '阴性阳性率统计',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList35',
        path: '/home',
        name: '项目周转统计',
        iconType: 'antd',
        icon: '',
        query: {},
      }
    ]
  },
  {
    id: 'userManage14',
    path: '/home15',
    name: '生信管理',
    iconType: 'antd',
    icon: 'book',
    query: {},
    children: [{
      id: 'userManageList36',
      path: '/home',
      name: '生信分析任务管理',
      iconType: 'antd',
      icon: '',
      query: {},
    }, {
      id: 'userManageList37',
      path: '/home',
      name: '医学分析任务管理',
      iconType: 'antd',
      icon: '',
      query: {},
    }]
  },
  {
    id: 'userManage15',
    path: '/home16',
    name: '业务配置',
    iconType: 'antd',
    icon: 'team',
    query: {},
    children: [{
        id: 'userManageList38',
        path: '/home',
        name: '样本类型',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList39',
        path: '/home',
        name: '接头管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList40',
        path: '/home',
        name: 'SOP管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList41',
        path: '/home',
        name: '二代检测项目配置',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList42',
        path: '/home',
        name: '一代检测项目配置',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList43',
        path: '/home',
        name: '检测产品配置',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList44',
        path: '/home',
        name: '实验配置',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList45',
        path: '/home',
        name: '药物管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList46',
        path: '/home',
        name: '疾病管理',
        iconType: 'antd',
        icon: '',
        query: {},
      }
    ]
  },
  {
    id: 'userManage16',
    path: '/home17',
    name: '客户管理',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
        id: 'userManageList47',
        path: '/home',
        name: '客户档案管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList48',
        path: '/home',
        name: '客户报价单管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList49',
        path: '/home',
        name: '查询统计及导入导出',
        iconType: 'antd',
        icon: '',
        query: {},
      }
    ]
  },

  {
    id: 'userManage17',
    path: '/home18',
    name: '试剂耗材管理',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
        id: 'userManageList47',
        path: '/home',
        name: '试剂耗材档案管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList48',
        path: '/home',
        name: '试剂耗材供应商管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList49',
        path: '/home',
        name: '试剂耗材入库和出库',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList50',
        path: '/home',
        name: '试剂耗材库存查询和预警',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList51',
        path: '/home',
        name: '试剂耗材操作日记',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList52',
        path: '/home',
        name: '导入导出功能',
        iconType: 'antd',
        icon: '',
        query: {},
      }
    ]
  },

  {
    id: 'userManage18',
    path: '/home19',
    name: '仪器管理',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
        id: 'userManageList53',
        path: '/home',
        name: '仪器档案管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList54',
        path: '/home',
        name: '仪器维修，检定，报废管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList55',
        path: '/home',
        name: '仪器查询统计',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList56',
        path: '/home',
        name: '批量导入导出',
        iconType: 'antd',
        icon: '',
        query: {},
      },

    ]
  },

  {
    id: 'userManage19',
    path: '/home20',
    name: '质量控制管理',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
        id: 'userManageList57',
        path: '/home',
        name: '室内质控记录和查询',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList58',
        path: '/home',
        name: '室内质控图生成',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList59',
        path: '/home',
        name: '室间质控记录和查询',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList60',
        path: '/home',
        name: '室间质控图生成',
        iconType: 'antd',
        icon: '',
        query: {},
      },
    ]
  },

  {
    id: 'userManage20',
    path: '/home21',
    name: '订单管理',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
        id: 'userManageList61',
        path: '/home',
        name: '订单查询',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList62',
        path: '/home',
        name: '补样和完善',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList63',
        path: '/home',
        name: '查看和下载报告',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList64',
        path: '/home',
        name: '订单状态更新',
        iconType: 'antd',
        icon: '',
        query: {},
      },
    ]
  },
  {
    id: 'userManage21',
    path: '/home22',
    name: '新增订单',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
      id: 'userManageList62',
      path: '/home',
      name: '新增送样',
      iconType: 'antd',
      icon: '',
      query: {},
    }, ]
  },
  {
    id: 'userManage22',
    path: '/home23',
    name: '新冠订单',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
      id: 'userManageList63',
      path: '/home',
      name: '新冠订单新增',
      iconType: 'antd',
      icon: '',
      query: {},
    }, ]
  },
  {
    id: 'userManage23',
    path: '/home24',
    name: '检测产品',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
      id: 'userManageList64',
      path: '/home',
      name: '检测产品查看',
      iconType: 'antd',
      icon: '',
      query: {},
    }, ]
  },
  {
    id: 'userManage24',
    path: '/home25',
    name: '检测样本',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
      id: 'userManageList65',
      path: '/home',
      name: '检测样本状态查看',
      iconType: 'antd',
      icon: '',
      query: {},
    }, ]
  },
  {
    id: 'userManage25',
    path: '/home26',
    name: '打包运输',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
      id: 'userManageList66',
      path: '/home',
      name: '打包运输物流信息填写',
      iconType: 'antd',
      icon: '',
      query: {},
    }, ]
  },
  {
    id: 'userManage26',
    path: '/home27',
    name: '角色管理',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
      id: 'userManageList67',
      path: '/home',
      name: '角色新增，修改，查询',
      iconType: 'antd',
      icon: '',
      query: {},
    }, ]
  },
  {
    id: 'userManage27',
    path: '/home28',
    name: '用户管理',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
      id: 'userManageList68',
      path: '/home',
      name: '用户新增，修改，查询',
      iconType: 'antd',
      icon: '',
      query: {},
    }, ]
  },
  {
    id: 'userManage28',
    path: '/home29',
    name: '部门管理',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
      id: 'userManageList68',
      path: '/home',
      name: '部门新增，修改，查询',
      iconType: 'antd',
      icon: '',
      query: {},
    }, ]
  },
  {
    id: 'userManage29',
    path: '/home30',
    name: '菜单管理',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
      id: 'userManageList69',
      path: '/home',
      name: '菜单新增，修改',
      iconType: 'antd',
      icon: '',
      query: {},
    }, ]
  },
  {
    id: 'userManage30',
    path: '/home31',
    name: '邮箱配置',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
      id: 'userManageList70',
      path: '/home',
      name: '编辑发送报告邮箱配置',
      iconType: 'antd',
      icon: '',
      query: {},
    }, ]
  },
  {
    id: 'userManage31',
    path: '/home32',
    name: '数据权限管理',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
      id: 'userManageList71',
      path: '/home',
      name: '数据权限配置',
      iconType: 'antd',
      icon: '',
      query: {},
    }, ]
  },
  {
    id: 'userManage32',
    path: '/home33',
    name: '数据字典',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
      id: 'userManageList72',
      path: '/home',
      name: '数据字典新增，修改',
      iconType: 'antd',
      icon: '',
      query: {},
    }, ]
  }
];