export const leftNavData = [{
    id: 'home',
    path: '/storeManage/echarts',
    name: '首页',
    iconType: 'antd',
    icon: 'home',
    query: {},
  },
  {
    id: 'userManage',
    path: '/userManage/list',
    name: '待办事项',
    iconType: 'antd',
    icon: 'team',
    query: {},

  },

  {
    id: 'userManage20',
    path: '/home22',
    name: '项目中心',
    iconType: 'antd',
    icon: 'user',
    query: {},
    children: [{
        id: 'userManageList52',
        path: '/home',
        name: '订单列表',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList53',
        path: '/home',
        name: '新冠订单',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList41',
        path: '/home',
        name: '返样管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList51',
        path: '/home',
        name: '重新送样',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList61',
        path: '/home',
        name: '打包列表',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList71',
        path: '/home',
        name: '变动订单',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList81',
        path: '/home',
        name: '项目异常',
        iconType: 'antd',
        icon: '',
        query: {},
      },
    ]
  },


  {
    id: 'userManage2',
    path: '/home3',
    name: '收样管理',
    iconType: 'antd',
    icon: 'form',
    query: {},
    children: [{
        id: 'userManageList9',
        path: '/home',
        name: '样本接收',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList10',
        path: '/home',
        name: '样本拆分',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList11',
        path: '/home',
        name: '异常处理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList12',
        path: '/home',
        name: '样本查询',
        iconType: 'antd',
        icon: '',
        query: {},
      }

    ]
  },
  {
    id: 'userManage1',
    path: '/home2',
    name: '样本库管理',
    iconType: 'antd',
    icon: 'user',
    query: {},
    children: [{
        id: 'userManageList2',
        path: '/home',
        name: '样本入库',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList3',
        path: '/home',
        name: '样本出库',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList4',
        path: '/home',
        name: '容器设置',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList5',
        path: '/home',
        name: '样本出库详情',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList6',
        path: '/home',
        name: '样本入库详情',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList7',
        path: '/home',
        name: '样本库列表',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList8',
        path: '/home',
        name: '样本库视图',
        iconType: 'antd',
        icon: '',
        query: {},
      },
    ]
  },
  {
    id: 'userManage10',
    path: '/home11',
    name: '实验进度',
    iconType: 'antd',
    icon: 'apartment',
    query: {},

  },
  {
    id: 'userManage32',
    path: '/home33',
    name: '核酸提取',
    iconType: 'antd',
    icon: 'edit',
    query: {},

  },

  {
    id: 'userManage3',
    path: '/home4',
    name: 'NGS平台',
    iconType: 'antd',
    icon: 'copy',
    query: {},
    children: [{
      id: 'userManageList131',
      path: '/home',
      name: '文库建库',
      iconType: 'antd',
      icon: '',
      query: {},
    }, {
      id: 'userManageList132',
      path: '/home',
      name: '文库捕获',
      iconType: 'antd',
      icon: '',
      query: {},
    }, {
      id: 'userManageList133',
      path: '/home',
      name: '混样上机',
      iconType: 'antd',
      icon: '',
      query: {},
    }, {
      id: 'userManageList134',
      path: '/home',
      name: '生信分析',
      iconType: 'antd',
      icon: '',
      query: {},
    }, {
      id: 'userManageList135',
      path: '/home',
      name: '医学报告',
      iconType: 'antd',
      icon: '',
      query: {},
    }]
  },

  {
    id: 'userManage4',
    path: '/home5',
    name: '其他平台',
    iconType: 'antd',
    icon: 'scissor',
    query: {},
    children: [{
      id: 'userManageList141',
      path: '/home',
      name: '实验检测',
      iconType: 'antd',
      icon: '',
      query: {},
    }, {
      id: 'userManageList142',
      path: '/home',
      name: '生信分析',
      iconType: 'antd',
      icon: '',
      query: {},
    }, {
      id: 'userManageList143',
      path: '/home',
      name: '医学报告',
      iconType: 'antd',
      icon: '',
      query: {},
    }]
  },
  {
    id: 'userManage5',
    path: '/home6',
    name: '外包实验',
    iconType: 'antd',
    icon: 'snippets',
    query: {},
  },

  {
    id: 'userManage17',
    path: '/home18',
    name: '试剂耗材管理',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
        id: 'userManageList47',
        path: '/home',
        name: '试剂耗材档案管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList48',
        path: '/home',
        name: '试剂耗材供应商管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList49',
        path: '/home',
        name: '试剂耗材入库和出库',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList50',
        path: '/home',
        name: '试剂耗材库存查询和预警',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList51',
        path: '/home',
        name: '试剂耗材操作日记',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList52',
        path: '/home',
        name: '导入导出功能',
        iconType: 'antd',
        icon: '',
        query: {},
      }
    ]
  },

  {
    id: 'userManage18',
    path: '/home19',
    name: '仪器管理',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
        id: 'userManageList53',
        path: '/home',
        name: '仪器档案管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList54',
        path: '/home',
        name: '仪器维修，检定，报废管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList55',
        path: '/home',
        name: '仪器查询统计',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList56',
        path: '/home',
        name: '批量导入导出',
        iconType: 'antd',
        icon: '',
        query: {},
      },

    ]
  },

  {
    id: 'userManage6',
    path: '/home7',
    name: '质量管理文件管理',
    iconType: 'antd',
    icon: 'highlight',
    query: {},
    children: [{
        id: 'userManageList161',
        path: '/home',
        name: '文件发布，审核，废弃，版本',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList162',
        path: '/home',
        name: '培训文档管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList163',
        path: '/home',
        name: '文件查询统计',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList164',
        path: '/home',
        name: '批量导入导出',
        iconType: 'antd',
        icon: '',
        query: {},
      }
    ]
  },

  {
    id: 'userManage19',
    path: '/home20',
    name: '质量控制管理',
    iconType: 'antd',
    icon: 'edit',
    query: {},
    children: [{
        id: 'userManageList57',
        path: '/home',
        name: '室内质控记录和查询',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList58',
        path: '/home',
        name: '室内质控图生成',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList59',
        path: '/home',
        name: '室间质控记录和查询',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList60',
        path: '/home',
        name: '室间质控图生成',
        iconType: 'antd',
        icon: '',
        query: {},
      },
    ]
  },
  {
    id: 'userManage15',
    path: '/home16',
    name: '业务配置',
    iconType: 'antd',
    icon: 'team',
    query: {},
    children: [{
        id: 'userManageList38',
        path: '/home',
        name: '样本类型',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList39',
        path: '/home',
        name: '接头管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList40',
        path: '/home',
        name: 'SOP管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList41',
        path: '/home',
        name: '二代检测项目配置',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList42',
        path: '/home',
        name: '一代检测项目配置',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList43',
        path: '/home',
        name: '检测产品配置',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList44',
        path: '/home',
        name: '实验配置',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList45',
        path: '/home',
        name: '药物管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList46',
        path: '/home',
        name: '疾病管理',
        iconType: 'antd',
        icon: '',
        query: {},
      }
    ]
  },


  {
    id: 'userManage9',
    path: '/home10',
    name: '系统管理',
    iconType: 'antd',
    icon: 'alert',
    query: {},
    children: [{
        id: 'userManageList19',
        path: '/home',
        name: '角色管理',
        iconType: 'antd',
        icon: '',
        query: {},
      }, {
        id: 'userManageList20',
        path: '/home',
        name: '用户管理',
        iconType: 'antd',
        icon: '',
        query: {},
      }, {
        id: 'userManageList21',
        path: '/home',
        name: '部门管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList22',
        path: '/home',
        name: '菜单管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList23',
        path: '/home',
        name: '邮箱配置',
        iconType: 'antd',
        icon: '',
        query: {},
      }, {
        id: 'userManageList24',
        path: '/home',
        name: '数据权限管理',
        iconType: 'antd',
        icon: '',
        query: {},
      },
      {
        id: 'userManageList25',
        path: '/home',
        name: '数据字典',
        iconType: 'antd',
        icon: '',
        query: {},
      }
    ]
  },
];